# -*- cmake -*-
# Construct the viewer version number based on the indra/VIEWER_VERSION file

if (NOT DEFINED VIEWER_SHORT_VERSION) # will be true in indra/, false in indra/newview/
    # <FS:Ansariel> Use own version file to avoid LL's year-as-major-version thing
    # set(VIEWER_VERSION_BASE_FILE "${CMAKE_CURRENT_SOURCE_DIR}/newview/VIEWER_VERSION.txt")
    set(VIEWER_VERSION_BASE_FILE "${CMAKE_CURRENT_SOURCE_DIR}/newview/VIEWER_VERSION_FS.txt")

    if ( EXISTS ${VIEWER_VERSION_BASE_FILE} )
        file(STRINGS ${VIEWER_VERSION_BASE_FILE} VIEWER_FULL_VERSION REGEX "^[0-9]+\\.[0-9]+\\.[0-9]+")
        string(REPLACE "." ";" VERSION_PARTS ${VIEWER_FULL_VERSION})
        list(GET VERSION_PARTS 0 VIEWER_VERSION_MAJOR)
        list(GET VERSION_PARTS 1 VIEWER_VERSION_MINOR)
        list(GET VERSION_PARTS 2 VIEWER_VERSION_PATCH)
        list(LENGTH VERSION_PARTS VERSION_PARTS_LEN)
        if (VERSION_PARTS_LEN GREATER 3)
            list(GET VERSION_PARTS 3 VIEWER_VERSION_REVISION)
        else()
            set(VIEWER_VERSION_REVISION 0)
        endif()
        set(VIEWER_SHORT_VERSION "${VIEWER_VERSION_MAJOR}.${VIEWER_VERSION_MINOR}.${VIEWER_VERSION_PATCH}")
        message(STATUS "Building '${VIEWER_CHANNEL}' Version ${VIEWER_FULL_VERSION}")
    else ( EXISTS ${VIEWER_VERSION_BASE_FILE} )
        message(SEND_ERROR "Cannot get viewer version from '${VIEWER_VERSION_BASE_FILE}'") 
    endif ( EXISTS ${VIEWER_VERSION_BASE_FILE} )

    # <FS:PP>
    set(VIEWER_VERSION_LL_FILE "${CMAKE_CURRENT_SOURCE_DIR}/newview/VIEWER_VERSION.txt")
    if (EXISTS ${VIEWER_VERSION_LL_FILE})
        file(STRINGS ${VIEWER_VERSION_LL_FILE} VIEWER_VERSION_LL LIMIT_COUNT 1)
        string(STRIP "${VIEWER_VERSION_LL}" VIEWER_VERSION_LL)
        message(STATUS "Upstream viewer version: ${VIEWER_VERSION_LL}")
    endif ()
    # </FS:PP>

    set(VIEWER_CHANNEL_VERSION_DEFINES
        "LL_VIEWER_CHANNEL=${VIEWER_CHANNEL}"
        "LL_VIEWER_VERSION_MAJOR=${VIEWER_VERSION_MAJOR}"
        "LL_VIEWER_VERSION_MINOR=${VIEWER_VERSION_MINOR}"
        "LL_VIEWER_VERSION_PATCH=${VIEWER_VERSION_PATCH}"
        "LL_VIEWER_VERSION_BUILD=${VIEWER_VERSION_REVISION}"
        "FS_VIEWER_VERSION_GITHASH=${VIEWER_VERSION_GITHASH}"
        "LLBUILD_CONFIG=\"${CMAKE_BUILD_TYPE}\""
        )
endif (NOT DEFINED VIEWER_SHORT_VERSION)
