#!/bin/bash

export __GL_THREADED_OPTIMIZATIONS=1
export SDL_VIDEO_X11_DGAMOUSE=0

SCRIPTSRC=$(readlink -f "$0" || echo "$0")
RUN_PATH=$(dirname "${SCRIPTSRC}")/..
cd "${RUN_PATH}/extra" || exit 1

export LD_LIBRARY_PATH="${RUN_PATH}/extra/lib:${LD_LIBRARY_PATH}"

SAVED_LD_LIBRARY_PATH="${LD_LIBRARY_PATH}"

LLCRYPTO="$(pwd)/lib/libcrypto.so.1.0.0"
LLSSL="$(pwd)/lib/libssl.so.1.0.0"
if [ -f "${LLCRYPTO}" ]; then
    export LD_PRELOAD="${LD_PRELOAD}:${LLCRYPTO}"
fi
if [ -f "${LLSSL}" ]; then
    export LD_PRELOAD="${LD_PRELOAD}:${LLSSL}"
fi

FSJEMALLOC="$(pwd)/lib/libjemalloc.so"
if [ -f "${FSJEMALLOC}" ]; then
    export LD_PRELOAD="${LD_PRELOAD}:${FSJEMALLOC}"
fi

ARGS=()
for ARG in "$@"; do
    if [ "--skip-gridargs" != "$ARG" ]; then
        ARGS[${#ARGS[*]}]="$ARG"
    fi
done

exec bin/do-not-directly-run-mikostorm-bin "${ARGS[@]}"
