#pragma once

#define RESHADE_VERSION_FULL 6.7.3.0
#define RESHADE_VERSION_MAJOR 6
#define RESHADE_VERSION_MINOR 7
#define RESHADE_VERSION_REVISION 3
#define RESHADE_VERSION_BUILD 0

#define VERSION_STRING_FILE "6.7.3"
#define VERSION_STRING_PRODUCT "6.7.3 UNOFFICIAL"
