#ifndef LL_LLGLHEADERS_H
#define LL_LLGLHEADERS_H

#include "glad/glad.h"

#include <GL/glu.h>

#if LL_WINDOWS

#ifndef PFNWGLCREATECONTEXTATTRIBSARBPROC
#define PFNWGLCREATECONTEXTATTRIBSARBPROC
typedef HGLRC (APIENTRYP PFNWGLCREATECONTEXTATTRIBSARBPROC)(HDC hDC, HGLRC hShareContext, const int *attribList);
#endif

#ifndef PFNWGLGETGPUIDSAMDPROC
#define PFNWGLGETGPUIDSAMDPROC
typedef UINT (APIENTRYP PFNWGLGETGPUIDSAMDPROC)(UINT maxCount, UINT *ids);
#endif

#ifndef PFNWGLGETGPUINFOAMDPROC
#define PFNWGLGETGPUINFOAMDPROC
typedef INT (APIENTRYP PFNWGLGETGPUINFOAMDPROC)(UINT id, UINT property, GLenum dataType, UINT size, void *data);
#endif

#ifndef PFNWGLGETCONTEXTGPUIDAMDPROC
#define PFNWGLGETCONTEXTGPUIDAMDPROC
typedef UINT (APIENTRYP PFNWGLGETCONTEXTGPUIDAMDPROC)(HGLRC hglrc);
#endif

#ifndef PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC
#define PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC
typedef HGLRC (APIENTRYP PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC)(UINT id);
#endif

#ifndef PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC
#define PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC
typedef HGLRC (APIENTRYP PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC)(UINT id, HGLRC hShareContext, const int *attribList);
#endif

#ifndef PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC
#define PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC
typedef BOOL (APIENTRYP PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC)(HGLRC hglrc);
#endif

#ifndef PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC
#define PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC
typedef BOOL (APIENTRYP PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC)(HGLRC hglrc);
#endif

#ifndef PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC
#define PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC
typedef HGLRC (APIENTRYP PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC)(void);
#endif

#ifndef PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC
#define PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC
typedef VOID (APIENTRYP PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC)(HGLRC dstCtx, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
#endif

#ifndef PFNWGLSWAPINTERVALEXTPROC
#define PFNWGLSWAPINTERVALEXTPROC
typedef BOOL (APIENTRYP PFNWGLSWAPINTERVALEXTPROC)(int interval);
#endif

#ifndef PFNWGLGETSWAPINTERVALEXTPROC
#define PFNWGLGETSWAPINTERVALEXTPROC
typedef int (APIENTRYP PFNWGLGETSWAPINTERVALEXTPROC)(void);
#endif

#ifndef PFNWGLCHOOSEPIXELFORMATARBPROC
#define PFNWGLCHOOSEPIXELFORMATARBPROC
typedef BOOL (APIENTRYP PFNWGLCHOOSEPIXELFORMATARBPROC)(HDC, const int*, const float*, UINT, int*, UINT*);
#endif

#ifndef PFNWGLGETPIXELFORMATATTRIBIVARBPROC
#define PFNWGLGETPIXELFORMATATTRIBIVARBPROC
typedef BOOL (APIENTRYP PFNWGLGETPIXELFORMATATTRIBIVARBPROC)(HDC, int, int, UINT, const int*, int*);
#endif

extern PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB;
extern PFNWGLGETGPUIDSAMDPROC            wglGetGPUIDsAMD;
extern PFNWGLGETGPUINFOAMDPROC           wglGetGPUInfoAMD;
extern PFNWGLGETCONTEXTGPUIDAMDPROC      wglGetContextGPUIDAMD;
extern PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC  wglCreateAssociatedContextAMD;
extern PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC wglCreateAssociatedContextAttribsAMD;
extern PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC  wglDeleteAssociatedContextAMD;
extern PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC wglMakeAssociatedContextCurrentAMD;
extern PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC wglGetCurrentAssociatedContextAMD;
extern PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC wglBlitContextFramebufferAMD;
extern PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB;
extern PFNWGLGETPIXELFORMATATTRIBIVARBPROC wglGetPixelFormatAttribivARB;
extern PFNWGLSWAPINTERVALEXTPROC    wglSwapIntervalEXT;
extern PFNWGLGETSWAPINTERVALEXTPROC wglGetSwapIntervalEXT;

#endif

#ifndef GL_DEPTH_CLAMP
#define GL_DEPTH_CLAMP 0x864F
#endif

#ifndef GL_NVX_gpu_memory_info
#define GL_NVX_gpu_memory_info
#define GL_GPU_MEMORY_INFO_DEDICATED_VIDMEM_NVX          0x9047
#define GL_GPU_MEMORY_INFO_TOTAL_AVAILABLE_MEMORY_NVX    0x9048
#define GL_GPU_MEMORY_INFO_CURRENT_AVAILABLE_VIDMEM_NVX  0x9049
#define GL_GPU_MEMORY_INFO_EVICTION_COUNT_NVX            0x904A
#define GL_GPU_MEMORY_INFO_EVICTED_MEMORY_NVX            0x904B
#endif

#ifndef GL_ATI_meminfo
#define GL_ATI_meminfo
#define GL_VBO_FREE_MEMORY_ATI                     0x87FB
#define GL_TEXTURE_FREE_MEMORY_ATI                 0x87FC
#define GL_RENDERBUFFER_FREE_MEMORY_ATI            0x87FD
#endif

#if defined(TRACY_ENABLE) && LL_PROFILER_ENABLE_TRACY_OPENGL
    #include <tracy/TracyOpenGL.hpp>
#endif

#endif
